python_library(
    name="dt_learninghub",
)


python_distribution(
    name="tutor-learninghub",
    provides=setup_py(
        name="dt-tutor-learninghub",
        version="0.1.0",
        description="dt-tutor-learning plugin for Tutor",
        entry_points={"tutor.plugin.v0": ["dt_learninghub = tutorlearninghub.plugin"]},
    ),
)

# TODO Add tutor dependency
