python_library(
    name="dt_devsetup",
)


python_distribution(
    name="devsetup",
    provides=setup_py(
        name="dt-tutor-devsetup",
        version="0.1.0",
        description="dt-devsetup-plugin plugin for Tutor",
        entry_points={"tutor.plugin.v0": ["dt_devsetup = tutordevsetup.plugin"]},
    ),
)

# TODO Add tutor dependency
